/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cofrepessoal;

import com.formdev.flatlaf.FlatDarkLaf;
import conexao.excluirCON;
import conexao.listarCON;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Diego
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaPrincipal() {
        initComponents();
    }
    
    public static void logoff (boolean escolha){
        TelaLogin tLogin = new TelaLogin();
        
        if (escolha = true){
            TelaLogin.LoggedUserClass.loginDispose = false;
            tLogin.setVisible(true);
            escolha = false;
        }
    }
    
    public static class tabelaLogins{
        public static String usuarioAtual;
        public static DefaultTableModel tblModel;
        public static Boolean confirmaExclusao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtCadastrar = new javax.swing.JButton();
        jbtLogoff = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jlbUsuarioLogado = new javax.swing.JLabel();
        jbtEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CofrePessoal - Pesquisa");
        setIconImages(null);
        setResizable(false);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Login", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTable1ComponentAdded(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jbtCadastrar.setText("Cadastrar");
        jbtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCadastrarActionPerformed(evt);
            }
        });

        jbtLogoff.setText("Logoff");
        jbtLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLogoffActionPerformed(evt);
            }
        });

        jbtExcluir.setText("Excluir");
        jbtExcluir.setEnabled(false);
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jlbUsuarioLogado.setText("Usuário:");

        jbtEditar.setText("Editar");
        jbtEditar.setEnabled(false);
        jbtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbUsuarioLogado)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jbtExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbUsuarioLogado)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtCadastrar)
                    .addComponent(jbtEditar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtExcluir)
                        .addComponent(jbtLogoff)))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCadastrarActionPerformed
        jTable1.clearSelection();
        jbtEditar.setEnabled(false);
        jbtExcluir.setEnabled(false);
        TelaCadastro tCadastro = new TelaCadastro();
        tCadastro.setVisible(true);               
    }//GEN-LAST:event_jbtCadastrarActionPerformed

    private void jTable1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTable1ComponentAdded

    }//GEN-LAST:event_jTable1ComponentAdded

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getSelectedRow() > -1)
        {
            jbtExcluir.setEnabled(true);
            jbtEditar.setEnabled(true);
        }
        else
        {
            jbtExcluir.setEnabled(false);
            jbtEditar.setEnabled(false);
        }
        
        if (jTable1.getSelectedRow() > -1 && evt.getClickCount() == 2)
        {
            TelaEditar.alterarLogins.validarLogin = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
            TelaEditar.alterarLogins.alterarDescricao = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            TelaEditar.alterarLogins.alterarLogin = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
            TelaEditar.alterarLogins.alterarSenha = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
            TelaEditar tEditar = new TelaEditar();
            tEditar.setVisible(true);    
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed
        excluirCON excluirCON = new excluirCON();
        excluirCON.excluirConexao(jTable1);
        
        if (TelaPrincipal.tabelaLogins.confirmaExclusao == true)
        {
        jbtExcluir.setEnabled(false);
        jbtEditar.setEnabled(false);
        }
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String labelUsuarioAtual = tabelaLogins.usuarioAtual.substring(0, 1).toUpperCase() + tabelaLogins.usuarioAtual.substring(1);
        jlbUsuarioLogado.setText("Usuário: " + labelUsuarioAtual);
        listarCON listarCON = new listarCON();
        listarCON.listarConexao(jTable1);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ImageIcon icon = new ImageIcon("src/safe.png");
        setIconImage(icon.getImage()); 
    }//GEN-LAST:event_formWindowActivated

    private void jbtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditarActionPerformed
        TelaEditar.alterarLogins.validarLogin = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        TelaEditar.alterarLogins.alterarDescricao = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        TelaEditar.alterarLogins.alterarLogin = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        TelaEditar.alterarLogins.alterarSenha = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        jbtExcluir.setEnabled(false);
        jbtEditar.setEnabled(false);
        TelaEditar tEditar = new TelaEditar();
        tEditar.setVisible(true);
    }//GEN-LAST:event_jbtEditarActionPerformed

    private void jbtLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLogoffActionPerformed
        int confirmarSaida = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "CofrePessoal", JOptionPane.YES_NO_OPTION);
        
        if (confirmarSaida == JOptionPane.YES_OPTION)
        {
            this.dispose();
            logoff(true);
        }
    }//GEN-LAST:event_jbtLogoffActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int confirmarSaida = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "CofrePessoal", JOptionPane.YES_NO_OPTION);
        
        if (confirmarSaida == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       FlatDarkLaf.setup();
         
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
       });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtCadastrar;
    private javax.swing.JButton jbtEditar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtLogoff;
    private javax.swing.JLabel jlbUsuarioLogado;
    // End of variables declaration//GEN-END:variables
}
